{
 "title": "SampleWeb",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HTTP Client Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Endpoint load speed wins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint) (sampleservice_wins_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint load times",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(httpclient_response_duration_seconds_bucket[5m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Page Load Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "SampleWeb HTTP RPS",
   "type": "timeseries",
   "description": "HTTP Requests Per Second (30s intervals)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg RPS (30sec window)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{page=\"/Index\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}