{
 "title": "prometheus-net",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": {
     "query": "label_values(http_requests_received_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory management",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_collection_count_total{instance =~ \"$instances\"}[30s])) by (generation) != 0",
     "legendFormat": "GC gen{{generation}}"
    },
    {
     "expr": "sum(process_working_set_bytes{instance =~ \"$instances\"})",
     "legendFormat": "Working Set"
    },
    {
     "expr": "sum(process_private_memory_bytes{instance =~ \"$instances\"})",
     "legendFormat": "Private"
    },
    {
     "expr": "sum(dotnet_total_memory_bytes{instance =~ \"$instances\"}) ",
     "legendFormat": ".NET Objects"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance =~ \"$instances\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "The duration of HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_num_threads{instance =~ \"$instances\"}) by (instance)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{instance =~ \"$instances\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance =~ \"$instances\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_handles{instance =~ \"$instances\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}